image: 192.168.179.44:5000/hyperdata20.4.1.0.0_virtualization:20221216_v1

ingressClassName: "nginx"

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

server:
  port: 8100
  servlet:
    contextPath: /hyperdata20

db:
  address: tiberolocaldns
  port: 8629
  sid: tibero

pvc:
  name: tibero-pvc-db
  mountPath: /db

resources:
  requests:
    cpu: 500m
    memory: 4Gi
  limits:
    cpu: 500m
    memory: 4Gi

proauth:
  address: hyperdata-lb-hd:28080

hyperdata:
  address: hyperdata-svc-hd
  port: 8080

loadBalancer:
  enabled: false
  #enabled: true
  #ip: 172.31.45.59  #하이퍼데이터 로드밸런서 ip랑 같아야 함
  ip: 192.168.220.110  #하이퍼데이터 로드밸런서 ip랑 같아야 함
  extport: 8500

logging:
  path: virtualization/logs

version:
  major: 20
