apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notebook-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notebook-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: notebook-controller-service-account
  namespace: {{ .Release.Namespace }}
