image: 192.168.179.44:5000/hyperdata20.4.1.0.0_tb:20221216_v1

loadbalancer:
  enabled: false
  ip: 192.168.173.62

db:
  persistentVolumeClaimName: tibero-pvc-db
  mountPath: /db

shmSize: 3Gi
memoryTarget: 6Gi

resources:
  requests:
    cpu: 1.5
    memory: 8Gi
  limits:
    cpu: 1.5
    memory: 8Gi
  storage: 40Gi

storageClassName:
  enabled: false
  name: "nfs-client-lsm"
