apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyperdata-mqtt-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.proxy.bodysize }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
    - http:
        paths:
        - path: /mqtt
          pathType: Prefix
          backend:
            service:
              name: hyperdata-svc-hd
              port:
                number: 2883
