apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tibero-studio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.proxy.bodysize }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.proxy.timeout }}"
spec:
  tls:
    - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
    - http:
        paths:
          - path: /tiberowebstudio/(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: service-tibero-sd 
              servicePort: 8000
    - http:
        paths:
          - path: /static/(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: service-tibero-sd 
              servicePort: 8000









