apiVersion: v1
kind: Service
metadata:
  name: service-tibero-sd                    
spec:
  type: NodePort
  selector:
    app: tibero-sd
  ports:
    - name: tbsd-lsnr
      nodePort: {{ .Values.service.port.tbsd_lsnr.nodePort }}
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: tbsd-proxy
      nodePort: {{ .Values.service.port.tbsd_proxy.nodePort }}
      port: 3000
      protocol: TCP
      targetPort: 3000

