apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gdb-ingress-bolt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
  - secretName: istio.hyperdata-nginx-ingress-nginx
  rules:
  - http:
      paths:
      - path: /bolt(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ template "neo4j.fullname" . }}
            port:
              number: 7687

