image: 192.168.179.44:5000/tbstudio_web:20221028_v1

proxy:
  bodysize: 10m
  # minutes
  timeout: 1800

service:
  port:
    tbsd_lsnr:
      nodePort: 30874
    tbsd_proxy:
      nodePort: 30894

resources:
  requests:
    cpu: 4
    memory: 8Gi
  limits:
    cpu: 4
    memory: 8Gi
