kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-default-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/log
  verbs:
  - get
  - list
  - watch
