apiVersion: v1
kind: Service
metadata:
  name: mlplatform-backend-svc
  labels:
    app: mlplatform-backend-svc
spec:
  ports:
  - name: server-port
    port: 18080
    targetPort: 18080
    protocol: TCP
  selector:
    app: mlplatform-backend-deploy
  type: ClusterIP
