apiVersion: v1
kind: Service
metadata:
  name: istio-ingress-gateway-external-svc
spec:
  type: ExternalName
  externalName: {{ .Values.kubernetes.istio.ingressgateway.service.name }}.{{ .Values.kubernetes.istio.ingressgateway.namespace }}.svc.cluster.local
