kind: Service
apiVersion: v1
metadata:
  # tibero cannot use dns name if name has minus sign.
  # kubernetes DNS name only use alphabet, number, minus sign(-)
  # DO NOT USE minus sign in here!
  name: tiberolocaldns
spec:
  selector:
    lb: tibero-db
  clusterIP: None
  #ports:
  #- name: port1
  #  port: 8628
  #  protocol: TCP
  #- name: port2
  #  port: 8629
  #  protocol: TCP
  #- name: port3
  #  port: 8630
  #  protocol: TCP

