apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: tibero-hd
  name: {{ .Values.db.persistentVolumeClaimName }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
  # storageClassName: csi-cephfs
  {{ if .Values.storageClassName.enabled }}
  storageClassName: {{ .Values.storageClassName.name }}
  {{ end }}
  volumeMode: Filesystem
